---
title: "rcode"
author: "Jingwei Ren"
date: "12/7/2019"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(survminer)
library(bayesSurv)
library(biostan)
library(rstan)
library(bayesplot)
library(tidybayes)
```

Descriptive analysis example

```{r}
data(leukemia, package = "survival")
leukemia <- as_data_frame(leukemia)
leukemia
```

stan weibull 

```{r}
stan_weibull_survival_model_file <- system.file('stan', 'weibull_survival_model.stan', package =  'biostan')
biostan::print_stan_file(stan_weibull_survival_model_file)
```


```{R}
stan_weibull_survival_model_code <- biostan::read_stan_file(stan_weibull_survival_model_file)
biostan::print_stan_code(stan_weibull_survival_model_code, section = "data")

stan_weibull_survival_model_data <-
    list(
        ## Number of event individuals
        Nobs = sum(leukemia$status == 1),
        ## Number of censored individuals
        Ncen = sum(leukemia$status == 0),
        ## Number of covariates
        M_bg = 1,
        ## Times for event individuals
        yobs = leukemia$time[leukemia$status == 1],
        ## Times for censored individuals
        ycen = leukemia$time[leukemia$status == 0],
        ## Covariates for event individuals as a matrix
        Xobs_bg = matrix(as.numeric(leukemia$x == "Maintained")[leukemia$status == 1]),
        ## Covariates for censored individuals as a matrix
        Xcen_bg = matrix(as.numeric(leukemia$x == "Maintained")[leukemia$status == 0])
        )
stan_weibull_survival_model_data

```


```{R}
stan_weibull_survival_model_fit <-
    rstan::stan(file = stan_weibull_survival_model_file,
                data = stan_weibull_survival_model_data)
```


```{R}
stan_weibull_survival_model_fit
```


```{r}
stan_weibull_survival_model_draws <- tidybayes::tidy_draws(stan_weibull_survival_model_fit)
stan_weibull_survival_model_draws


treatment_assignment <- c(as.numeric(leukemia$x == "Maintained")[leukemia$status == 1],
                          as.numeric(leukemia$x == "Maintained")[leukemia$status == 0])
treatment_assignment_df <-
    data_frame(obs = 1:23,
               treatment = treatment_assignment)
treatment_assignment_df



stan_weibull_survival_model_draws_yhat_uncens <-
    stan_weibull_survival_model_draws %>%
    select(alpha, mu,.chain, .iteration, .draw,`log_lik[1]`, `log_lik[2]`,`log_lik[3]`,`log_lik[4]`, `log_lik[5]`,
           `log_lik[6]`,`log_lik[7]`,`log_lik[8]`,`log_lik[9]`,`log_lik[10]`,`log_lik[11]`,`log_lik[12]`,`log_lik[13]`,`log_lik[14]`,`log_lik[15]`,`log_lik[16]`,`log_lik[17]`,`log_lik[18]`,`log_lik[19]`,`log_lik[20]`,`log_lik[21]`,`log_lik[22]`,`log_lik[23]`,`beta_bg[1]`,starts_with("yhat_uncens")) %>%
    gather(key = key, value = yhat_uncens, starts_with("yhat_uncens")) %>%
    separate(col = key, sep = "uncens", into = c("key","obs")) %>%
    select(-key) %>%
    ## Avoid using regular expressions with square brackets (syntax highlighter broke).
    ## https://stringr.tidyverse.org/articles/stringr.html
    mutate(obs = as.integer(str_sub(obs, 2, -2))) %>%
    left_join(y = treatment_assignment_df)



df = rbind(tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[1]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[2]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[3]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[4]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[5]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[6]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[7]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[8]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[9]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[10]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[11]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[12]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[13]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[14]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[15]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[16]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[17]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[18]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[19]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[20]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[21]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[22]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max),tapply(stan_weibull_survival_model_draws_yhat_uncens$`log_lik[23]`, stan_weibull_survival_model_draws_yhat_uncens$treatment, max))







ggplot(data = stan_weibull_survival_model_draws_yhat_uncens,
       mapping = aes(x = yhat_uncens, color = factor(treatment))) +
    geom_density(n = 512*10) +
    coord_cartesian(xlim = c(0,160)) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
          legend.key = element_blank(),
          plot.title = element_text(hjust = 0.5),
          strip.background = element_blank())

```




```{r}
## Constructor for treatment-specific survival function
construct_survival_function <- function(alpha, mu, beta, x) {
    function(t) {
        sigma_i <- exp(-1 * (mu + beta * x) / alpha)
        exp(- (t / sigma_i)^alpha)
    }
}

## Random functions
stan_weibull_survival_model_survival_functins <-
    stan_weibull_survival_model_draws %>%
    select(.chain, .iteration, .draw, alpha, mu, `beta_bg[1]`) %>%
    ## Simplify name
    rename(beta = `beta_bg[1]`) %>%
    ## Construct realization of random functions
    mutate(`S(t|1)` = pmap(list(alpha, mu, beta), function(a,m,b) {construct_survival_function(a,m,b,1)}),
           `S(t|0)` = pmap(list(alpha, mu, beta), function(a,m,b) {construct_survival_function(a,m,b,0)}))
stan_weibull_survival_model_survival_functins



## Apply all realizations
stan_weibull_survival_model_survival <-
    stan_weibull_survival_model_survival_functins %>%
    mutate(times_df = list(times_df)) %>%
    mutate(times_df = pmap(list(times_df, `S(t|1)`, `S(t|0)`),
                           function(df, s1, s0) {df %>% mutate(s1 = s1(t),
                                                               s0 = s0(t))})) %>%
    select(-`S(t|1)`, -`S(t|0)`) %>%
    unnest() %>%
    gather(key = treatment, value = survival, s1, s0) %>%
    mutate(treatment = factor(treatment,
                              levels = c("s1","s0"),
                              labels = c("Maintained","Nonmaintained")))

## Average on survival scale
stan_weibull_survival_model_survival_mean <-
    stan_weibull_survival_model_survival %>%
    group_by(treatment, t) %>%
    summarize(survival_mean = mean(survival),
              survival_95upper = quantile(survival, probs = 0.975),
              survival_95lower = quantile(survival, probs = 0.025))

ggplot(data = stan_weibull_survival_model_survival,
       mapping = aes(x = t, y = survival, color = treatment, group = interaction(.chain,.draw,treatment))) +
    geom_line(size = 0.1, alpha = 0.02) +
    geom_line(data = stan_weibull_survival_model_survival_mean,
              mapping = aes(y = survival_mean, group = treatment)) +
    geom_line(data = stan_weibull_survival_model_survival_mean,
              mapping = aes(y = survival_95upper, group = treatment),
              linetype = "dotted") +
    geom_line(data = stan_weibull_survival_model_survival_mean,
              mapping = aes(y = survival_95lower, group = treatment),
              linetype = "dotted") +
    facet_grid(. ~ treatment) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
          legend.key = element_blank(),
          plot.title = element_text(hjust = 0.5),
          strip.background = element_blank())




## Average on parameter space
stan_weibull_survival_model_average_parameters <-
    stan_weibull_survival_model_draws %>%
    summarize(alpha = mean(alpha),
              mu = mean(mu),
              beta = mean(`beta_bg[1]`))
stan_weibull_survival_model_average_parameters

```



```{r}
data(leukemia, package = "survival")
leukemia <- as_data_frame(leukemia)
leukemia

```


## unparametric model allocation


```{r}
d = leukemia %>%
  mutate(tobs = time,
         delta = status,
         x1 = x)

library(survival)
library(spBayesSurv)
library(coda)

###############################################################
# Independent DDP: Bayesian Nonparametric Survival Model
###############################################################
# MCMC parameters
nburn=500; nsave=500; nskip=0;
# Note larger nburn, nsave and nskip should be used in practice.
mcmc=list(nburn=nburn, nsave=nsave, nskip=nskip, ndisplay=1000);
prior = list(N=4, a0=2, b0=2);
# Fit the Cox PH model
res1 = anovaDDP(formula = Surv(tobs, delta)~x1, data=d, 
                prior=prior, mcmc=mcmc);

allo_list = NULL
for ( i in 1:500){
v501= cbind(res1$Tpred, leukemia$x) %>% 
  as.data.frame() %>% 
  select(V501)

time2 = cbind(res1$Tpred, leukemia$x) %>% 
  as.data.frame()

time2 = time2[,i]

time = cbind(time2,v501)


weight = res1$w %>%
  as.data.frame()

weighti = weight[,i]

weightJ = 1/weighti

weight = as.data.frame(cbind(weighti, weightJ))


control = time %>%
  filter(V501 ==1)

a = sum(control$time2>18)/nrow(control)

treat = time %>%
  filter(V501 ==2)

b = sum(treat$time2 >18)/nrow(treat)

p = ifelse(a > b, a, b)


control = time %>%
  filter(V501 ==1)

c = sum(control$time2 >28)/nrow(control)

treat = time %>%
  filter(V501 ==2)

d = sum(treat$time2 >28)/nrow(treat)

p2 = ifelse(c>d,c,d)


control = time %>%
  filter(V501 ==1)

c = sum(control$time2 >48)/nrow(control)

treat = time %>%
  filter(V501 ==2)

d = sum(treat$time2 >48)/nrow(treat)

p3 = ifelse(c>d,c,d)

control = time %>%
  filter(V501 ==1)

c = sum(control$time2 >58)/nrow(control)

treat = time %>%
  filter(V501 ==2)

d = sum(treat$time2 >58)/nrow(treat)

p4 = ifelse(c>d,c,d)



allo = weight[1,1]*p +weight[2,1]*p2 +weight[3,1]*p3 + weight[4,1]*p4

allo_list = c(allo_list,allo)
}

mean(allo_list)

```